### ISSUE TITLE
Error when trying to run brand new application

### ISSUE THREAD

**Issue by ernsyn** [mshima/generator-jhipster-multitenancy2#3]
I created a plain JHipster v6.1.2.

I then ran "jhipster --blueprint multitenancy2". Everything runs fine.

However, when I tried to run the application via "mvnw", I get the following error.

➜  mt2 git:(master) ./mvnw
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.multitenant:multitenant >---------------------
[INFO] Building Multitenant 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) > test-compile @ multitenant >>>
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (default-resources) @ multitenant ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 18 resources
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ multitenant ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 18 resources
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ multitenant ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-dependencyConvergence) @ multitenant ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.4:prepare-agent (pre-unit-tests) @ multitenant ---
[INFO] argLine set to -javaagent:/Users/john/.m2/repository/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4-runtime.jar=destfile=/Users/john/workspace/mt2/target/jacoco/test.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO]
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ multitenant ---
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ multitenant ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 76 source files to /Users/john/workspace/mt2/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[50,29] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[51,57] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[73,29] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[75,45] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[79,21] cannot find symbol
  symbol:   method setCompany(com.multitenant.domain.Company)
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[95,17] cannot find symbol
  symbol:   method setCompany(com.multitenant.domain.Company)
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[110,29] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[113,58] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[113,25] cannot find symbol
  symbol:   method getCompany()
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[131,29] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[134,58] cannot find symbol
  symbol:   method getCompany()
  location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[134,25] cannot find symbol
  symbol:   method getCompany()
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/service/dto/UserDTO.java:[79,28] cannot find symbol
  symbol:   method getCompany()
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/domain/Company.java:[67,13] cannot find symbol
  symbol:   method setCompany(com.multitenant.domain.Company)
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/domain/Company.java:[73,13] cannot find symbol
  symbol:   method setCompany(<nulltype>)
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/CompanyAspect.java:[47,33] cannot find symbol
  symbol:   method getCompany()
  location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/CompanyAspect.java:[49,68] cannot find symbol
  symbol:   method getCompany()
  location: variable user of type com.multitenant.domain.User
[INFO] 17 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.840 s
[INFO] Finished at: 2019-07-31T16:37:29+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project multitenant: Compilation failure: Compilation failure:
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[50,29] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[51,57] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[73,29] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[75,45] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[79,21] cannot find symbol
[ERROR]   symbol:   method setCompany(com.multitenant.domain.Company)
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[95,17] cannot find symbol
[ERROR]   symbol:   method setCompany(com.multitenant.domain.Company)
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[110,29] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[113,58] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[113,25] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[131,29] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[134,58] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable loggedInUser of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/UserAspect.java:[134,25] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/service/dto/UserDTO.java:[79,28] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/domain/Company.java:[67,13] cannot find symbol
[ERROR]   symbol:   method setCompany(com.multitenant.domain.Company)
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/domain/Company.java:[73,13] cannot find symbol
[ERROR]   symbol:   method setCompany(<nulltype>)
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/CompanyAspect.java:[47,33] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] /Users/john/workspace/mt2/src/main/java/com/multitenant/aop/company/CompanyAspect.java:[49,68] cannot find symbol
[ERROR]   symbol:   method getCompany()
[ERROR]   location: variable user of type com.multitenant.domain.User
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
➜  mt2 git:(master)

It seems that the code generator missed generating some codes. I was wondering whether this issue is due to me doing it wrongly? Or maybe it's a bug? 

Please advise.

**Comment by mshima** [comment]
Try to regenerate with 
```
jhipster --with-entities --blueprint multitenancy2
```

**Comment by ernsyn** [comment]
I tried and got the same error. 

DId you manage to generate an app without error? If so, how was it generated?

Do I generate a Jhipster app first then only running the command you suggested?

**Comment by mshima** [comment]
Generated first, got another error (not the one you got), regenerated ok.

Post the .yo and the .jhipster directory.

**Comment by ernsyn** [comment]
This is the contents of my .yo-rc.json

`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.multitenant",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "mt2",
    "packageName": "com.multitenant",
    "packageFolder": "com/multitenant",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "MDBlYjQyZWYzY2ZkNDdkMGQ2MzIyOWYzMTdmZTYzN2M2NTU5OWUwNDI1Yzc4MWM5Zjc2YTYxYmQ3Njg2YjdjY2U0MzY0MTRjZWZiOTBiNTRlNTFjYTVjZDVkMWY4MmIwMmE3MjMzZDYzNzZlNmYwYmY2N2YzODNiYWFkMGMyNTc=",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-multitenancy2",
        "version": "0.0.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprint": "generator-jhipster-multitenancy2",
    "blueprintVersion": "0.0.0"
  },
  "generator-jhipster-multitenancy2": {
    "tenantChangelogDate": "20190802065149",
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "mt2",
    "packageName": "com.multitenant",
    "packageFolder": "com/multitenant",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "MDBlYjQyZWYzY2ZkNDdkMGQ2MzIyOWYzMTdmZTYzN2M2NTU5OWUwNDI1Yzc4MWM5Zjc2YTYxYmQ3Njg2YjdjY2U0MzY0MTRjZWZiOTBiNTRlNTFjYTVjZDVkMWY4MmIwMmE3MjMzZDYzNzZlNmYwYmY2N2YzODNiYWFkMGMyNTc=",
    "enableTranslation": true,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "tenantManagement": true,
    "experimentalTenantManagement": false,
    "tenantName": "Company"
  }
}`

My .jhipster has one json, Company.json. Below are the contents of that file.

`{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "users",
            "otherEntityName": "user",
            "relationshipType": "one-to-many",
            "otherEntityField": "login",
            "relationshipValidateRules": "required",
            "ownerSide": true,
            "otherEntityRelationshipName": "company"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20190802065149",
    "dto": "no",
    "searchEngine": false,
    "service": "serviceClass",
    "entityTableName": "company",
    "databaseType": "sql",
    "jpaMetamodelFiltering": false,
    "pagination": "pagination"
}`
