### ISSUE TITLE
Localization strings missing / not correct with different tenant name

### ISSUE THREAD

**Issue by shwabnitz** [mshima/generator-jhipster-multitenancy2#7]
By choosing "Tenant" instead of "Company" as tenant name the following localisations are not configured properly.

1. The menu entry for the entity expects "global.menu.entities.adminTenant". In global.json ..."adminTenantManagement" is used.
2. In user-management.component.html the translation string is "userManagementTenant" but should be "userManagement.tenant". The related entry in "user-management.json" is missing.
3. In user-management-detail.component.html the translation string is "userManagementTenant" but should be "userManagement.tenant"
4. In navbar.component.html the translation string is "global.menu.admin.admin/company-management" and should be something like "global.menu.admin.tenantManagement" (double "admin" and "." instead of "/".
5. In "adminTenantManagement.json" a key is "adminTenantManagement" but in the rest of the code referenced as "adminTenant"

**Comment by mshima** [comment]
Seems everything is fixed.
